<?php
if( function_exists('acf_add_local_field_group') ):

    // Key Lesson Takeaway fields
    acf_add_local_field_group(array(
        'key' => 'group_5f0349af20871',
        'title' => 'Key Lesson Takeaways',
        'fields' => array(
            array(
                'key' => 'field_5f034a0a394ce',
                'label' => 'Tips for success',
                'name' => 'tips_for_success',
                'type' => 'repeater',
                'instructions' => '3+ of the most important info/advice',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5f034af4394d0',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Tip',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f034af4394d0',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f034a67394cf',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_5f0357274bc4e',
                'label' => 'Common Mistakes',
                'name' => 'common_mistakes',
                'type' => 'repeater',
                'instructions' => '3+ of the most common mistakes',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5f0357274bc4f',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Mistake',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f0357274bc4f',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f0357274bc50',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_5f0357784bc51',
                'label' => 'Quick Tips',
                'name' => 'quick_tips',
                'type' => 'repeater',
                'instructions' => 'Any extra info or advice',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5f0357784bc52',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Quick Tip',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f0357784bc52',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f0357784bc53',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_5f035df9e89bf',
                'label' => 'What To Practice',
                'name' => 'what_to_practice',
                'type' => 'repeater',
                'instructions' => 'Any extra info or advice',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_you_should_be_able_to_item',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add something to practice',
                'sub_fields' => array(
                    array(
                        'key' => 'field_you_should_be_able_to_item',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f035df9e89c1',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_you_should_be_able_to',
                'label' => 'You Should Be Able To',
                'name' => 'you_should_be_able_to',
                'type' => 'repeater',
                'instructions' => 'Expected outcomes/goals of this lesson',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_you_should_be_able_to_title',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Outcome/Goal',
                'sub_fields' => array(
                    array(
                        'key' => 'field_you_should_be_able_to_title',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_you_should_be_able_to_content',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 1,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sfwd-lessons',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'skills',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));


    // Puck Level for Skills
    acf_add_local_field_group(array(
        'key' => 'group_5f10b29f6a623',
        'title' => 'Skill',
        'fields' => array(
            array(
                'key' => 'field_5f10b2a8e99b8',
                'label' => 'Puck Level',
                'name' => 'puck_level',
                'type' => 'radio',
                'instructions' => 'Frequency of use.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    1 => '1',
                    2 => '2',
                    3 => '3',
                    4 => '4',
                    5 => '5',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_video_code',
                'label' => 'Video Code',
                'name' => 'video_code',
                'type' => 'wysiwyg',
                'tabs' => 'text',
                'toolbar' => 'basic',
                'instructions' => 'The video code to embed.',
                'required' => 0,
                'conditional_logic' => 0,
                'allow_null' => 0,
                'default_value' => '',
                'return_format' => 'value',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'skills',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
endif;
?>